German translation 82% complete
Skoice/skoice pull request #34
Opened 2022-06-16 12:56 UTC by moonbear46

Hey, I would like to offer you an almost complete translation of Skoice in my native language. I will be happy to make the missing translations with an explanation of your color code. I am at your disposal for any question.

2022-06-17 19:05 UTC, LucasCdry requested changes
Thanks for the hard work! We really appreciate it.

Here are some issues:
- Please stick to German capitalizing rules for titles (only the first letter, if I am right).
- Try to be consistent as much as possible (`Nähe Voice-Chat`, `Voice-Chat in der Nähe`, `Proximity Voice Chat`, `Proximity-Voice-Chat`).
- Try to avoid English words as much as possible (for instance, in French, we translated `Lobby` into the French for `Main voice channel`).
- Address some requested changes to align with a recent commit I have made.

Concerning the color code, here is the rules:
- Gray is our base color (&7), no need to put it at the beginning of messages though.
- Anything between quotation marks is colored in yellow (`&e`).
Emphasized words are either green (`&a`, for an intended behaviour) or red (`&c`, for an unexpected behaviour). I don't know anything about German grammar, but for English and French, the coloured part is:
  - the verb *or* the `-ed` form of the verb if there is one ("Your Minecraft account is __already **linked**__ to Discord.")
  - the adverb if there is one ("Your Minecraft account is __**already** linked__ to Discord.")
  - the direct object that follows the verb ("You have __not provided **a valid code**__.")
  - "not" when there is a negation ("You have __**not** provided a valid code__.")

If those rules cannot be applied to the German language, do not forget our keyword: **consistency**!

Thanks again for the effort you have put in!

2022-06-17 21:56 UTC, LucasCdry commented on src/main/resources/lang/DE.yml
> +      description: "Manage other parameters."
Needs to be translated

2022-06-21 13:20 UTC, moonbear46 commented on src/main/resources/lang/DE.yml
> +      description: "**General:**\n• Discover a whole new and intuitive configuration interface.\n• Let us choose the best distances for your personal use of Skoice in the \"Mode\" menu.\n• Link your
Hey, how can I suggest my modifications to this?

2022-06-21 14:54 UTC, moonbear46 commented
Hey Lucas! I corrected according to your feedback and finished all the translations thanks to your explanation of the color code. Feel free to give me more feedback!

2022-06-22 10:33 UTC, LucasCdry requested changes
Hey! Just a few missing translations to align with my latest commits. I will merge your work as soon as those have been made.

2022-06-23 17:41 UTC, merged